---
- name: AWS Infrastructure Provisioning Exercise
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: "us-east-1"
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    instance_type: "t3.micro"
    key_name: "my_key"
    ami_id: "ami-h9321892h289"
    project_name: "interview-demo"

  tasks:
    - name: Create VPC
      # fill in logic here

    - name: Create Subnet
      # fill in logic here

    - name: Launch EC2 instance
      # fill in logic here

    - name: Debug instance private IP
      # fill in logic here
